### PR TITLE
Add heatmap to crosscheckfingerprints

### PR DESCRIPTION
**Pull request by matthdsm**
Add LOD heatmap to crosscheckfingerprints

- [x] This comment contains a description of changes (with reason)

### CODE REVIEW

**Comment by matthdsm** [comment]
This should close #2385

**Comment by vladsavelyev** [comment]
Thanks a lot for working on that! Huh, I actually also started working on that. Preparing two PRs, the second one improving the heatmap code, allowing it to accept a dict of dicts as input.

**Comment by vladsavelyev** [comment]
My version: https://github.com/MultiQC/MultiQC/pull/2388

**Comment by matthdsm** [comment]
Superseded by #2388

**Comment by matthdsm** [comment]
Thanks for the work @vladsavelyev

**Pull request closed without merging**
