### PR TITLE
Adding mgikit plugin

### PR DESCRIPTION
**Pull request by ziadbkh**
- [X] This comment contains a description of changes (with reason)
This pull request is to add a plugin for [mgikit](https://sagc-bioinformatics.github.io/mgikit/) tool. 
- [X] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [X] Code is tested and works locally (including with `--strict` flag)
- [X] `docs/modulename.md` is created
- [X] Everything that can be represented with a plot instead of a table is a plot
- [X] Report sections have a description and help text (with `self.add_section`)
- [X] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [X] Each table column has a different colour scale to its neighbour, which relates to the data (e.g. if high numbers are bad, they're red)
- [X] Module does not do any significant computational work

### CODE REVIEW

**Comment by vladsavelyev** [comment]
Thanks you for the PR! I'd like to merge it for the upcoming release. 

I wonder if you could allow repo maintainers to push into the PR branch? There should be a checkbox somewhere on the right pane.

**Comment by ziadbkh** [comment]
It seems that this option is not available if the PR is coming from a repo from an organisation. Is there another way I can help with?

**Comment by vladsavelyev** [comment]
I created a new PR from your branch so I can push into it: https://github.com/MultiQC/MultiQC/pull/3023

I re-worked it slightly to make a module vs. plugin. Modules generally don't use cli and kwargs, but rather a custom config section e.g.: 

```yaml
mgikit:
      keep_core_samples: false
```

It also seems like it's more natural to parse sample stats from `*.mgikit.sample_stats` as they are not rounded up. Though no info for lanes there, I wonder it is output into a yet another file, e.g. `*.mgikit.lane_stats`?

**Comment by vladsavelyev** [comment]
Going to merge https://github.com/MultiQC/MultiQC/pull/3023 and close this PR. Thank you a lot for your contribution! Feel free to submit new PRs if you want to change or add anything to the module code. Or to create another module!

**Pull request closed without merging**
