### PR TITLE
Hifiasm: account for lines with no asterisk

### PR DESCRIPTION
**Pull request by mbeavitt**
- [x] This comment contains a description of changes (with reason)

- [x] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [x] Code is tested and works locally (including with `--strict` flag)
- [x] `docs/README.md` is updated with link to below
- [x] `docs/modulename.md` is created
- [x] Everything that can be represented with a plot instead of a table is a plot
- [x] Report sections have a description and help text (with `self.add_section`)
- [x] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [x] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [x] Module does not do any significant computational work

The hifiasm module doesn't account for kmer graphs which do not start with an asterisk. It is unknown if this is a recent update, or just something that occurs on small input data. 

I have updated it to check whether a kmer graph line starts with an asterisk, and use a different strategy if not.

### CODE REVIEW

**Comment by mbeavitt** [comment]
ah, weird, I PR'd with my work account. sorry about that. hope it's all fine anyhow

**Comment by vladsavelyev** [comment]
@multiqc-bot changelog

**Review by vladsavelyev — APPROVED** [review]
Thanks a lot for the fix!

**Comment by mbeavitt** [comment]
glad to be of service!

Officially my first ever contribution to open source code 😄

**Comment by ewels** [comment]
Congratulations @mbeavitt - welcome to the team! 🎉

**Pull request merged**
