### PR TITLE
picard: Add table with all metrics to VariantCallingMetrics section

### LINKED ISSUE #2857: Add remaining metrics to Picard submodule's `VariantCallingMetrics`
### Description of feature

Hello,

Picard outputs `VariantCallingDetailMetrics`, which MultiQC's Picard submodule takes a subset of. Can we please have the rest of them? I'm particularly interested in the het/hom ratio and n/%GTQ0 metrics being added, but I see no reason not to add them all.

The `HSMetrics` command displays most of, if not all, the metrics from its respective output (in a table under its own section), and I'm hoping the same could be done for the variant-calling metric collection part.

Thank you :)

(Side note: sorry if this is the wrong issue type. I couldn't see module-specific feature requests under the list of templates)

### PR DESCRIPTION
**Pull request by spaul91**
Added table section to Picard's `VariantCallingMetrics` subsection, displaying all of the metrics imported. Changes loosely based on `HsMetrics.py` - we wanted the same thing (i.e. a table with all of the metrics), but for variant calling metrics. Please see the comment below for example output, which uses input from https://github.com/MultiQC/test-data.

Fixes #2857 

- [x] This comment contains a description of changes (with reason)

- [x] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [x] Code is tested and works locally (including with `--strict` flag)
- [x] Everything that can be represented with a plot instead of a table is a plot
- [ ] Report sections have a description and help text (with `self.add_section`)
  - Table section does not have one, same as in `HsMetrics.py`. I wasn't sure what to put here under the help text, and it seemed self-explanatory to me
- [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
  - We needed all of the metrics visible
- [ ] Each table column has a different colour scale to its neighbour, which relates to the data (e.g. if high numbers are bad, they're red)
  - All use default `GnBu` scheme
- [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by spaul91** [comment]
Command + STDOUT:

```
multiqc --force --verbose --strict test-data/data/modules/picard/VariantCallingMetrics/

/// MultiQC 🔍 v1.26.dev0

[2024-09-27 14:36:58] multiqc.core.tmp_dir                               [DEBUG  ]  Using new temporary directory: /tmp/tmpz7q3_kim
[2024-09-27 14:36:58] root                                               [DEBUG  ]  Logging to file: /tmp/tmpz7q3_kim/multiqc.log
[2024-09-27 14:36:58] multiqc.core.update_config                         [DEBUG  ]  This is MultiQC v1.26.dev0
[2024-09-27 14:36:58] multiqc.core.update_config                         [DEBUG  ]  Running Python 3.10.13 (main, Jan 19 2024, 16:01:26) [GCC 9.4.0]
[2024-09-27 14:36:58] urllib3.connectionpool                             [DEBUG  ]  Starting new HTTPS connection (1): api.multiqc.info:443
[2024-09-27 14:36:58] urllib3.connectionpool                             [DEBUG  ]  https://api.multiqc.info:443 "GET /version?version_multiqc=1.26.dev0&version_python=3.10.13&operating_system=Linux&is_docker=False&is_singularity=False&is_conda=False&is_ci=False&is_notebook=False HTTP/11" 200 178
[2024-09-27 14:36:58] multiqc.core.version_check                         [DEBUG  ]  Latest MultiQC version is v1.25, released 2024-09-17
[2024-09-27 14:36:58] multiqc.multiqc                                    [DEBUG  ]  Working dir : /home/pauls4/workspace/development
[2024-09-27 14:36:58] multiqc.multiqc                                    [DEBUG  ]  Template    : default
[2024-09-27 14:36:58] multiqc.multiqc                                    [INFO   ]  Strict mode specified. Will exit early if a module or a template crashed, and will give warnings if anything is not optimally configured in a module or a template.
[2024-09-27 14:36:58] multiqc.multiqc                                    [DEBUG  ]  Command used: /home/pauls4/workspace/development/MultiQC/venv/bin/multiqc --force --verbose --strict test-data/data/modules/picard/VariantCallingMetrics/
[2024-09-27 14:36:58] multiqc.core.file_search                           [INFO   ]  Search path: /home/pauls4/workspace/development/test-data/data/modules/picard/VariantCallingMetrics
[2024-09-27 14:36:58] multiqc.core.file_search                           [DEBUG  ]  Analysing modules: custom_content, ccs, ngsderive, purple, conpair, isoseq, lima, peddy, somalier, methylqa, mosdepth, phantompeakqualtools, qualimap, bamdst, preseq, hifiasm, quast, qorts, rna_seqc, rockhopper, rsem, rseqc, busco, bustools, goleft_indexcov, gffcompare, disambiguate, supernova, deeptools, sargasso, verifybamid, mirtrace, happy, mirtop, glimpse, gopeaks, homer, hops, macs2, theta2, snpeff, gatk, htseq, bcftools, featurecounts, fgbio, dragen, dragen_fastqc, dedup, pbmarkdup, damageprofiler, mapdamage, biobambam2, jcvi, mtnucratio, picard, vep, bakta, prokka, qc3C, nanoq, nanostat, samblaster, samtools, bamtools, sambamba, ngsbits, pairtools, sexdeterrmine, seqera_cli, eigenstratdatabasetools, jellyfish, vcftools, longranger, stacks, varscan2, snippy, umicollapse, umitools, truvari, megahit, ganon, bbmap, bismark, biscuit, diamond, hicexplorer, hicup, hicpro, salmon, kallisto, slamdunk, star, hisat2, tophat, bowtie2, bowtie1, hostile, cellranger, snpsplit, odgi, vg, pangolin, nextclade, freyja, humid, kat, leehom, librarian, nonpareil, adapterremoval, bbduk, clipandmerge, cutadapt, flexbar, sourmash, kaiju, bracken, kraken, malt, motus, trimmomatic, sickle, skewer, sortmerna, biobloomtools, fastq_screen, afterqc, fastp, fastqc, sequali, filtlong, prinseqplusplus, pychopper, porechop, pycoqc, minionqc, anglerfish, multivcfanalyzer, clusterflow, checkqc, bcl2fastq, bclconvert, interop, ivar, flash, seqyclean, optitype, whatshap, spaceranger, xenome, xengsort, metaphlan, seqwho, software_versions
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Summary of files that were skipped by the search: |skipped_module_specific_max_filesize: 2|, |skipped_no_match: 1|
[2024-09-27 14:36:58] multiqc.core.exec_modules                          [DEBUG  ]  Running module: custom_content
[2024-09-27 14:36:58] multiqc.core.exec_modules                          [DEBUG  ]  No samples found: custom_content
[2024-09-27 14:36:58] multiqc.core.exec_modules                          [DEBUG  ]  Running module: picard
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool AlignmentSummaryMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool BaseDistributionByCycleMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool IlluminaBasecallingMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool IlluminaLaneMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool CrosscheckFingerprints
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool ExtractIlluminaBarcodes
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool GcBiasMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool HsMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool InsertSizeMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool MarkDuplicates
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool MarkIlluminaAdapters
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_histogram.txt
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool OxoGMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool QualityByCycleMetrics
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_histogram_1.txt
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool QualityScoreDistributionMetrics
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_histogram_2.txt
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool QualityYieldMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool RnaSeqMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool RrbsSummaryMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool TargetedPcrMetrics
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool ValidateSamFile
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool VariantCallingMetrics
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_picard_variantCalling.txt
[2024-09-27 14:36:58] multiqc.report                                     [ERROR  ]  LINT: >picard/VariantCallingMetrics.py< HTML ID was a duplicate (picard_variantcallingmetrics-1) ## 
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [INFO   ]  Found 1 VariantCallingMetrics reports
[2024-09-27 14:36:58] multiqc.modules.picard.picard                      [DEBUG  ]  Running picard tool WgsMetrics
[2024-09-27 14:36:58] multiqc.base_module                                [DEBUG  ]  picard: deleting attribute self.sample_names
[2024-09-27 14:36:58] multiqc.base_module                                [DEBUG  ]  picard: deleting attribute self.general_stats_headers
[2024-09-27 14:36:58] multiqc.base_module                                [DEBUG  ]  picard: deleting attribute self.general_stats_data
[2024-09-27 14:36:58] multiqc.base_module                                [DEBUG  ]  picard: deleting attribute self.samples_parsed_by_tool
[2024-09-27 14:36:58] multiqc.core.software_versions                     [DEBUG  ]  Reading software versions from config.software_versions
[2024-09-27 14:36:58] multiqc.core.write_results                         [DEBUG  ]  Rendering plots
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_general_stats.txt
[2024-09-27 14:36:58] multiqc.core.write_results                         [DEBUG  ]  Exporting plot data to files
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_variantcallingmetrics.txt
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_variantCallingMetrics_variant_type_Total.txt
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_variantCallingMetrics_variant_type_Known.txt
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_variantCallingMetrics_variant_type_Novel.txt
[2024-09-27 14:36:58] multiqc.report                                     [DEBUG  ]  Wrote data file picard_variantCallingMetrics_variant_label.txt
[2024-09-27 14:36:58] multiqc.core.write_results                         [DEBUG  ]  Moving data file from '/tmp/tmpz7q3_kim/multiqc_data' to '/home/pauls4/workspace/development/multiqc_data'
[2024-09-27 14:36:58] multiqc.core.write_results                         [INFO   ]  Data        : multiqc_data
[2024-09-27 14:36:58] multiqc.core.write_results                         [DEBUG  ]  Compressing plot data
[2024-09-27 14:36:59] multiqc.core.write_results                         [INFO   ]  Report      : multiqc_report.html   (overwritten)
[2024-09-27 14:36:59] multiqc.core.write_results                         [DEBUG  ]  Report HTML written to /home/pauls4/workspace/development/multiqc_report.html
[2024-09-27 14:36:59] multiqc.multiqc                                    [ERROR  ]  Found 1 linting errors!
LINT: >picard/VariantCallingMetrics.py< HTML ID was a duplicate (picard_variantcallingmetrics-1) ## 
[2024-09-27 14:36:59] multiqc.multiqc                                    [INFO   ]  MultiQC complete
```

**Comment by spaul91** [comment]
Here's a screenshot of the output. I wasn't allowed to attach raw HTML to a comment...

multiqc_picard_variantcalling_testoutput

**Comment by spaul91** [comment]
Screenshot of example output - couldn't attach raw HTML

multiqc_picard_variantcalling_testoutput

**Comment by vladsavelyev** [comment]
Thank you for the PR! 

Please select a subset of the most useful metrics that would be displaied by default, and mark the rest with `hidden: True`. For your runs, you can configure MultiQC to display everything in the table: https://multiqc.info/docs/reports/customisation/#hiding-columns, however, we can't display tables so wide in the reports by default.

**Comment by ewels** [comment]
Another option is to make some more bar plots. Several of these columns seem to be subcategories and a total - these can be stacked bar plots and then removed from the table.

Tables should basically be a last resort really, as they require the most effort to interpret.

**Comment by spaul91** [comment]
Hi, thanks for taking a look :) I've decided to go with @vladsavelyev 's suggestion and trim down the number of columns shown by default - I've used [this post on the GATK website](https://gatk.broadinstitute.org/hc/en-us/articles/360035531572-Evaluating-the-quality-of-a-germline-short-variant-callset) as a guide to choose the ones to keep. There are now 7, hoping this is minimal enough.

We've decided against adding more plots, since we're mostly interested in the QC threshold functionality you get with tables, which we're planning to configure locally.

Thanks again for the suggestions, and taking a look at the PR.

- Sophie

**Review by vladsavelyev — APPROVED** [review]
Looks good!

**Comment by vladsavelyev** [comment]
Thanks for the contribution 👍

**Pull request merged**
