### PR TITLE
BCLConvert: Add index, project names to sample statistics and calculate mean quality for lane statistics.

### PR DESCRIPTION
**Pull request by rernst**
We were missing some fields in the MultiQC reports when doing conversion evaluations. I have added them to the module since I think others might find them usefull as well. I have added the following fields and try to follow existing code as much as possible:
- Sample Statistics table:
  - Index
  - Project 
-  Lane Statistics:
   - Mean Quality Score

### CODE REVIEW

**Review by vladsavelyev — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution! Really nice addition to the module.

I'm testing with the test data now:

```sh
git clone https://github.com/MultiQC/test-data
multiqc test-data/data/modules/bclconvert -fv -m bclconvert
```

And it looks liek the lane mean quality score seems to be too high: 

Screenshot 2024-01-20 at 00 03 09

I wonder if it is being summed up but not divided properly to get an average?

**Comment by rernst** [comment]
You are right, fixed it by using `sample["_calculated_yield"]` when calculating the `calculated_quality_score_sum` for lanes. Since `lane["_calculated_yield"]` contains a sum this greatly increased the `calculated_quality_score_sum`.

Screenshot 2024-01-22 at 13 09 05

**Review by vladsavelyev — APPROVED** [review]
Awesome, thanks for the quick fix!

**Review by ewels — APPROVED** [review]
Great addition, thanks!

**Comment by ewels** [comment]
GitHub actions are playing up, but happy to merge once CI is ✅

**Pull request merged**
