### PR TITLE
Add UMICollapse module

### LINKED ISSUE #2813: UMICollapse
### Name of the tool

UMICollapse

### Tool homepage

https://github.com/Daniel-Liu-c0deb0t/UMICollapse

### Tool description

Algorithms for efficiently collapsing reads with Unique Molecular Identifiers

### Tool output

[SRR19887568.umi_dedup.sorted_UMICollapse.log](https://github.com/user-attachments/files/16881147/SRR19887568.umi_dedup.sorted_UMICollapse.log)

### Log filename pattern

_UMICollapse.log

### Data suitable for MultiQC plot(s)

_No response_

### Most interesting data for the General Stats table

_No response_

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

### PR DESCRIPTION
**Pull request by siddharthab**
Fixes #2813.

See https://github.com/nf-core/rnaseq/issues/1087 for broader
discussion.

### CODE REVIEW

**Comment by siddharthab** [comment]
I have not looked into the testing infrastructure from the test-data repository. The tests I have included in the PR are satisfactory to me. Please let me know what else you would like to see.

**Comment by vladsavelyev** [comment]
This look great! Thank you for a very clean code. Special thanks for adding a proper test - that's better than an example in test-data.

**Comment by siddharthab** [comment]
Thank you for the quick look over!

**Comment by vladsavelyev** [comment]
We still need an example in test-data though. Used in some of tests, and it just allows me to run and review the module ;)

Added your example here: https://github.com/MultiQC/test-data/commit/9069ed966b32a4a49b4c42854d1ee3ac190c9dbb

**Review by vladsavelyev — APPROVED** [review]

**Pull request merged**
