### PR TITLE
Update docs to work with Astro 4

### PR DESCRIPTION
**Pull request by mashehu**
Changes required for dependency updates on the website. See https://github.com/MultiQC/website/pull/85

### CODE REVIEW

**Comment by ewels** [comment]
This is quite an irritating change, as it effectively breaks local development for anything involving images.

Is there no way to support relative image paths?

**Comment by mashehu** [comment]
okay, I think I found a work around 💡

**Comment by ewels** [comment]
Nice! Now just need to remember not to use the more obvious relative path. But that should be fine, as it won't work in the preview and can check the syntax of the other ones that do.. 😅 

Thank you!

**Comment by ewels** [comment]
@multiqc-bot changelog

**Review by ewels — APPROVED** [review]
Thanks!

**Pull request merged**
