### PR TITLE
Add CRISPResso2

### PR DESCRIPTION
**Pull request by olgabot**
This PR adds functionality for CRISPResso2 outputs. One of the input files is a zip which was problematic for using `pandas.read_csv` so I did `os.path.join` to get the original filename, which I don't know if that's what you want. Also I didn't see pandas in the dependencies so we'll see if that stays...

2019-08-14_crispresso2_multiqc_with_table_v3

## If this PR is for a new module
 - [ ] There is example tool output for tools in the https://github.com/ewels/MultiQC_TestData repository
 - [ ] Code is tested and works locally (including with `--lint` flag)
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated
 - [x] `docs/README.md` is updated with link to below
 - [x] `docs/modulename.md` is created
 - [ ] Everything that can be represented with a plot instead of a table is a plot
 - [ ] Report sections have a description and help text (with `self.add_section`)
 - [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
 - [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
 - [ ] Module does not do any significant computational work

(Can remove the ac8e7b4 commit, sorry)

### CODE REVIEW

**Comment by lucapinello** [comment]
Very cool @olgabot !

**Comment by lucapinello** [comment]
Sure, let me check with Kendell early next week (he is currently on
vacation).

**Comment by ewels** [comment]
Nice! As you guessed, I'd prefer to drop the pandas dependency if possible. The FastQC module already handles zip files, so you can dig into that code if you want an example:
https://github.com/ewels/MultiQC/blob/26076d71a0d7c65f8f189765b2ec82f454306706/multiqc/modules/fastqc/fastqc.py#L46-L68

Please add some test data to https://github.com/ewels/MultiQC_TestData so that the automatic tests will run ✅

**Comment by ewels** [comment]
Ping @olgabot 😃 I'm going to do a PR marathon soon, aiming to get a release out. Any updates?

**Pull request closed without merging**
