### PR TITLE
nanoq: Change lineplots for barplots

### PR DESCRIPTION
**Pull request by dialvarezs**
- [x] This comment contains a description of changes (with reason)

This PR updates one of the plots in the nanoq module, changing it from a line plot to a bar plot. The line plot is not the best option for visualizing nanoq quality output, primarily because it only reports counts for selected quality thresholds rather than for every possible quality value. Additionally, the line plot represents values only as percentages, difficulting comparison of yields across multiple samples. This type of plot is also used in the NanoStat module, a very similar tool.

Below is an example of the current plot:
nanoq_lines

And here is the updated plot produced by this PR:
nanoq_bars

### CODE REVIEW

**Comment by vladsavelyev** [comment]
Awesome stuff!! Thanks a lot for the contribution 🙏

**Comment by vladsavelyev** [comment]
@dialvarezs would it make sense to modify the read lengths plot to a barplot as well?

**Review by vladsavelyev — APPROVED** [review]

**Comment by dialvarezs** [comment]
@vladsavelyev Yes, you're right, that would make sense. I will update the length plot as well.

**Comment by vladsavelyev** [comment]
🔥 
Thank you again!

**Pull request merged**
