### PR TITLE
Samtools: Add support for `markdup`

### PR DESCRIPTION
**Pull request by clintval**
Closes https://github.com/MultiQC/MultiQC/issues/1862

This draft PR begins to implement a parser for the new `samtools markdup` statistics data:

- https://www.htslib.org/doc/samtools-markdup.html#STATISTICS

I have elements of this code working in a private repo, but want to signal intent to polish this work up for MultiQC proper by opening this draft PR.

I have a few personal TODOs before I finish:

- [x] Ensure this works on text file output
- [ ] Ensure this works on JSON file output
- [ ] Ensure this works on JSON stdout redirect (log file)
- [ ] Ensure this works on text stdout redirect (log file)
- [ ] Ensure the bar chart columns always sum to the actual number of SAM records read/written

Typical TODOs:

- [ ] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [ ] Code is tested and works locally (including with `--strict` flag)
- [ ] `docs/README.md` is updated with link to below
- [ ] `docs/modulename.md` is created
- [x] Everything that can be represented with a plot instead of a table is a plot
- [x] Report sections have a description and help text (with `self.add_section`)
- [x] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by Andy-B-123** [comment]
Very excited for this!!!

**Comment by ewels** [comment]
@multiqc-bot changelog

**Comment by ewels** [comment]
@multiqc-bot changelog

**Comment by ewels** [comment]
@multiqc-bot changelog

**Comment by ewels** [comment]
Ah right, [GitHub is down](https://www.githubstatus.com/incidents/pxg3dz4yg7lp) 🙈 😅  Sorry for the changelog spam.

**Comment by clintval** [comment]
Ha, thanks @Andy-B-123, you've given me a bit of energy to go and finish this ;)

**Comment by vladsavelyev** [comment]
Thanks for the PR!

I finalized it, taking into account @matthdsm's effort https://github.com/MultiQC/MultiQC/pull/2422

I didn't do the JSON support and other types of outputs, as we don't have test examples of those (if you have those handy, please share or contribute to https://github.com/MultiQC/test-data - I'll add support immediately!)

**Comment by vladsavelyev** [comment]
@multiqc-bot changelog

**Comment by matthdsm** [comment]
JSON test data has arrived!
https://github.com/MultiQC/test-data/pull/316

**Pull request merged**
