### PR TITLE
new module: samtools/markdup

### PR DESCRIPTION
**Pull request by matthdsm**
Add new module for samtools/markdup

- [x] This comment contains a description of changes (with reason)

- [x] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [] Code is tested and works locally (including with `--strict` flag)
- [] `docs/README.md` is updated with link to below
- [] `docs/modulename.md` is created
- [] Everything that can be represented with a plot instead of a table is a plot
- [ ] Report sections have a description and help text (with `self.add_section`)
- [ ] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [ ] Each table column has a different colour scale to its neighbour, which relates to the data (eg. if high numbers are bad, they're red)
- [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by matthdsm** [comment]
@vladsavelyev, can I get an intermediary review?
I'm not really sure anymore what I'm doing 😅 
This isn't nearly as advanced as @clintval 's version, but I need this module

**Comment by matthdsm** [comment]
xref https://github.com/MultiQC/test-data/pull/315

**Comment by vladsavelyev** [comment]
So there are two in-progress pull requests now instead of one 😅 Thanks for working on it, I'll take a look! Probably will continue from @clintval's one and cherry-pick your unique changes there.

x-refs: 
issue: https://github.com/MultiQC/MultiQC/issues/1862
first PR: https://github.com/MultiQC/MultiQC/pull/2254

**Comment by matthdsm** [comment]
Sorry about that 😅 I didn’t want to rush you so I thought I could contribute. A wise man once said:
“Be the PR you want to see”

( I think it was Phil)

**Comment by vladsavelyev** [comment]
> “Be the PR you want to see”

That worked! One PR is worth 10 issues, and two PRs make me jump into it right away :D

Alright, I effectively merged it with https://github.com/MultiQC/MultiQC/pull/2254

**Comment by vladsavelyev** [comment]
One thing I'm not 100% sure about is whether we should double the "pair" counts. I like the idea of sticking to the originally reported numbers as is, but the bar plot makes less sense when you have pairs and single reads mixed up 🤔 

Are we sure that samtools markdup doesn't count every _alignment_, so we should expect both left and right to be accounted for in the `pair` numbers, as long as there were records for both in the BAM file?

**Comment by clintval** [comment]
> One thing I'm not 100% sure about is whether we should double the "pair" counts. I like the idea of sticking to the originally reported numbers as is, but the bar plot makes less sense when you have pairs and single reads mixed up 🤔
> 
> Are we sure that samtools markdup doesn't count every _alignment_, so we should expect both left and right to be accounted for in the `pair` numbers, as long as there were records for both in the BAM file?

Your questions are good and I've tried auditing the code to absolutely determine the bar chart is not misleading the viewer (e.g. we aren't double counting reads in multiple categories). I would want us to understand this carefully before proposing we merge the PR. Perhaps we could reach out to the maintainers for some quick clarification?

I am pretty sure we should not be doubling any of the counts as I think they are all from the "alignment" perspective (not read, or read pair).

**Comment by vladsavelyev** [comment]
> Your questions are good and I've tried auditing the code to absolutely determine the bar chart is not misleading the viewer (e.g. we aren't double counting reads in multiple categories). I would want us to understand this carefully before proposing we merge the PR. Perhaps we could reach out to the maintainers for some quick clarification?

Makes sense! If you feel like it, it would be great to reach out. Though I'd still merge now, it's enough time to add possible fixes before the next MultiQC release 😅 

> I am pretty sure we should not be doubling any of the counts as I think they are all from the "alignment" perspective (not read, or read pair).

Agree!

**Pull request closed without merging**
