### PR TITLE
ngsbits: add submodule samplegender

### PR DESCRIPTION
**Pull request by peterpru**
This PR aims to add the output of ngs-bits SampleGender to the multiqc html and multiqc_data.json output.

- [x] This comment contains a description of changes (with reason)

- [x] There is example tool output for tools in the <https://github.com/MultiQC/test-data> repository or attached to this PR
- [x] Code is tested and works locally (including with `--strict` flag)
- [x] Everything that can be represented with a plot instead of a table is a plot
- [x] Report sections have a description and help text (with `self.add_section`)
- [x] There aren't any huge tables with > 6 columns (explain reasoning if so)
- [x] Module does not do any significant computational work

### CODE REVIEW

**Comment by peterpru** [comment]
Data shows up in the report:
image

**Comment by peterpru** [comment]
Data shows up in multiqc html output:
image

**Comment by peterpru** [comment]
The output in the html looks good, but in the the multiqc_data.json it looks like a string with extra characters in the report_general_stats_data section, although I expected something like:
image


image

**Comment by vladsavelyev** [comment]
Argh, sorry about the table json export bug. Should be fixed through https://github.com/MultiQC/MultiQC/pull/2879

**Comment by vladsavelyev** [comment]
By the way, I wonder if you have a test example of samplegender output to add into https://github.com/MultiQC/test-data/tree/main/data/modules/ngsbits?

**Comment by vladsavelyev** [comment]
Did not intend to close the PR - resolving https://github.com/MultiQC/MultiQC/pull/2879 closed it automatically. Reopened.

Thanks a lot for working on it! If you share a test example, would be able to review and merge.

**Comment by peterpru** [comment]
> Did not intend to close the PR - resolving #2879 closed it automatically. Reopened.
> 
> Thanks a lot for working on it! If you share a test example, would be able to review and merge.

Thanks for the review and the bug fix! I will add sample data 👍

**Comment by peterpru** [comment]
Output is now as expected:
image

**Comment by peterpru** [comment]
@vladsavelyev , I have opened a PR for the test data here: https://github.com/MultiQC/test-data/pull/336

**Comment by vladsavelyev** [comment]
Thanks for the test data!

Regarding the new section, can it be harmonized with other ngsbits sections? Title, description. Add color scales to columns. Use labels 
Screenshot 2024-09-30 at 18 07 02

Ideally also adding some help to all the sections on how to use the data would be a great bonus!

**Comment by peterpru** [comment]
Color and formatting updated to fit the other ngs bits modules.

image

**Comment by vladsavelyev** [comment]
Looks great now! But I'd hide by default all but "Predicted Gender" in the general stats. We aim at adding a minimal (1-2) amount of columns from each module, because the general stats table summarizes metrics across many modules, and it would get too wide in real life workflows. It can be customized with `table_columns_visible` https://docs.seqera.io/multiqc/reports/customisation#hiding-columns

**Review by vladsavelyev — APPROVED** [review]

**Pull request merged**
